version: 2

sources:
  - name: data_lake_raw
    schema: data_lake_raw
    loader: kinesis

    tables:
      - name: events
        indentifier: events
        description: Tabela de Eventos
        column:
          - name: event_id
            description: Id do evento
            tests:
              - not_null
              - unique
          - name: event_timestamp
            description: Timestamp em que o evento ocorreu
            tests:
              - not_null 